# Generated by Django 4.1.4 on 2022-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Notebook name')),
                ('price', models.IntegerField(verbose_name='Notebook price')),
                ('img', models.ImageField(upload_to='media', verbose_name='Notebook img')),
            ],
        ),
    ]
